-- =============================================================================
-- La Kuku Chicken — 0003: product image storage
--
-- Bucket policy: PUBLIC READ, STAFF WRITE.
--
-- Product photos are shown to every visitor, so the bucket must be publicly
-- readable. Uploads are NOT public: only authenticated staff whose role is
-- recorded in admin_profiles may insert, replace or delete objects.
--
-- Unauthenticated users therefore cannot upload, overwrite or delete anything.
-- There is no `USING (true)` policy on any write operation.
--
-- Uploaded object names are generated by the application (a UUID + a
-- whitelisted extension), never taken from the browser-supplied filename, so
-- path traversal and extension spoofing are not possible from the client side.
-- The first path segment is pinned to `products/` by the policy below, so an
-- upload cannot escape the bucket into other application paths.
-- =============================================================================

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'product-images',
  'product-images',
  true,
  -- 5 MB ceiling. Well above a good product photo, well below an abuse vector.
  5242880,
  -- Explicit allow-list. SVG is deliberately excluded: SVG is an XML document
  -- that can carry script, and is served as an active document type.
  array['image/jpeg', 'image/png', 'image/webp']
)
on conflict (id) do update
  set public             = excluded.public,
      file_size_limit    = excluded.file_size_limit,
      allowed_mime_types = excluded.allowed_mime_types;

-- Public can read product photos.
drop policy if exists "product images are publicly readable" on storage.objects;
create policy "product images are publicly readable"
  on storage.objects
  for select
  using (bucket_id = 'product-images');

-- Staff may upload. Path is restricted to the products/ prefix.
drop policy if exists "staff can upload product images" on storage.objects;
create policy "staff can upload product images"
  on storage.objects
  for insert
  to authenticated
  with check (
    bucket_id = 'product-images'
    and public.is_staff()
    and (storage.foldername(name))[1] = 'products'
  );

-- Staff may replace an existing photo. Both the old and new object must be in
-- the correct folder, otherwise a staff member could rename an object out of
-- the managed area.
drop policy if exists "staff can update product images" on storage.objects;
create policy "staff can update product images"
  on storage.objects
  for update
  to authenticated
  using (
    bucket_id = 'product-images'
    and public.is_staff()
    and (storage.foldername(name))[1] = 'products'
  )
  with check (
    bucket_id = 'product-images'
    and public.is_staff()
    and (storage.foldername(name))[1] = 'products'
  );

-- Only a full admin may delete an image file.
drop policy if exists "admin can delete product images" on storage.objects;
create policy "admin can delete product images"
  on storage.objects
  for delete
  to authenticated
  using (
    bucket_id = 'product-images'
    and public.is_admin()
    and (storage.foldername(name))[1] = 'products'
  );
